### ISSUE TITLE
Document that zlib source is required for installing nokogiri

### ISSUE THREAD

**Issue by jeremiahsnapp** [sparklemotion/nokogiri.org-tutorials#29]
A number of people (especially those using Ubuntu 12.04) are having problems installing nokogiri when all they need to do is install zlib source on their system.

```
sudo apt-get install zlib1g-dev
OR
sudo yum install zlib-devel
```

Please add this to the install tutorial somewhere.

nokogiri 1.6.6 should at least provide better error output showing the dependency.

Reference: https://github.com/sparklemotion/nokogiri/issues/1225#issue-54807205

**Comment by flavorjones** [comment]
Done, see 3d13d67b120c4e7ee9688353f113e468f988f6cf
