### ISSUE TITLE
Nokogiri on OS X 10.10

### ISSUE THREAD

**Issue by sebkkom** [sparklemotion/nokogiri.org-tutorials#37]
No other way to install Nokogiri works for me but this: http://stackoverflow.com/a/26459447/1175943

`gem install nokogiri -- \
--with-iconv-lib=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/lib \
--with-iconv-include=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include`

Maybe we should update the installation documentation to include this scenario too?

**Comment by flavorjones** [comment]
@sebkkom Thanks for bringing this up.

Can you explain what your scenario is, exactly? I don't yet understand why this was necessary, and so can't effectively document when this needs to be done.

**Comment by sebkkom** [comment]
@flavorjones Unfortunately I am on El Capitan now so can't test again but I had recently upgraded to 10.10 and Nokigiri just stopped working. Only way to bring it back was to do what was mentioned in the SO answer.

I take it it's not that much of a common problem so maybe the documentation is ok without it. :)

**Comment by flavorjones** [comment]
Thanks for following up. Again, I'm hesitant to turn the tutorial into a Stack-Overflow-style grab-bag of suggestions that anecdotally worked for individuals without understanding the underlying problem and judging what's the best way to solve that problem.
