### ISSUE TITLE
Tag this repo's commits to match nokogiri releases?

### ISSUE THREAD

**Issue by carols10cents** [sparklemotion/nokogiri.org-tutorials#42]
Hi! Thank you to all of yinz who maintain these docs, I've used them a whole bunch :heart: :heart: :heart: 

I recently tried to deploy an app that's a little bit old to a new infrastructure. The app uses nokogiri 1.5.11, and the installation on the production box failed the first time I tried it. The error message helpfully linked
to http://www.nokogiri.org/tutorials/installing_nokogiri.html, and that page helpfully said at the top "(If you need support for installing earlier versions of Nokogiri, you may want to take a look at the git history for [this document](https://github.com/sparklemotion/nokogiri.org-tutorials/blob/master/content/installing_nokogiri.md).)"

But when I went and looked at the history, I realized that I had no idea which commit was the last one when 1.5.11 was the newest version of nokogiri. I eventually compared release dates and commit dates and figured out that [this was probably the state of the doc at that time](https://github.com/sparklemotion/nokogiri.org-tutorials/blob/a88c4b537ede6708e26f9fa6cc812b77c6c7b97b/content/installing_nokogiri.md) and I was able to solve my problem.

It would be super awesome and nice to have tags in this repo that corresponded to releases of nokogiri, so that I could go to https://github.com/sparklemotion/nokogiri.org-tutorials/tags, pick the version I'm looking at, and then look at the files in the state they were at that point in time.

I would try to do this and send a PR, but I'm not aware of any way I can send a PR that is just tags???? Would a list of commits that I _would_ tag, if I could, be helpful? Or would you just have to check my work anyway, thus not really saving any time over a maintainer doing it?

**Comment by flavorjones** [comment]
@carols10cents Thanks for the love!

Hmm. If you'd like to track down the commits for each Nokogiri version, and put them in this issue, that'd be a great start. It's easy to tag; and then we might even be able to do something more interesting, like keep old versions around and format them as first-class artifacts in the web site?

**Comment by carols10cents** [comment]
> then we might even be able to do something more interesting, like keep old versions around and format them as first-class artifacts in the web site?

OOOH that would be awesome! Off to look up commits now :)

**Comment by carols10cents** [comment]
That wasn't too bad :) Here's what I've got, until the beginning of this repo, in an easily-unix-command-consumable format:

```
v1.6.6.4 1de3d4003b5b53ef507132ecd21e98aa566c1a74
v1.6.6.3 1de3d4003b5b53ef507132ecd21e98aa566c1a74
v1.6.6.2 3d13d67b120c4e7ee9688353f113e468f988f6cf
v1.6.6.1 3d13d67b120c4e7ee9688353f113e468f988f6cf
v1.6.6 3d13d67b120c4e7ee9688353f113e468f988f6cf
v1.6.5 6b424fc962165815cb341e6a67d3ad7ba7ee5e7d
v1.6.4.1 f1fd7d032461de242cb41124f3d29d6e8d7d7c33
v1.6.4 f1fd7d032461de242cb41124f3d29d6e8d7d7c33
v1.6.3.1 5565608288f443d5be82654a57b178d77afd0ed7
v1.6.3 5565608288f443d5be82654a57b178d77afd0ed7
v1.6.2.1 4f3acbb3f563a1f8056381d7f3c2f2b07ec28eb4
v1.6.2 4f3acbb3f563a1f8056381d7f3c2f2b07ec28eb4
v1.5.11 4f3acbb3f563a1f8056381d7f3c2f2b07ec28eb4
v1.6.1 4f3acbb3f563a1f8056381d7f3c2f2b07ec28eb4
v1.6.0 4f3acbb3f563a1f8056381d7f3c2f2b07ec28eb4
v1.5.10 4f3acbb3f563a1f8056381d7f3c2f2b07ec28eb4
v1.5.9 6d6734b9336381037b82ee41e5d0351203ad46cc
v1.5.8 8732b05220bd0bd129d27333a2a20d838ce95a14
v1.5.7 8732b05220bd0bd129d27333a2a20d838ce95a14
v1.5.6 8732b05220bd0bd129d27333a2a20d838ce95a14
v1.5.5 9bcf353361d56b8810bd596184ae278bccff9f83
v1.5.4 4146edbd1c87e1418a0a3b9403fe0b3b51e551be
v1.5.3 42015bb08fc292a650bcc9a7d08f2577fef07add
v1.5.2 2ccf9fd75e752efb99335d7438ae46584ea86826
v1.5.1 2ccf9fd75e752efb99335d7438ae46584ea86826
v1.5.0 c56a1e4b22071ac7b36c7bf3d2eb5d4e75588e9f
v1.4.7 c56a1e4b22071ac7b36c7bf3d2eb5d4e75588e9f
v1.4.6 c56a1e4b22071ac7b36c7bf3d2eb5d4e75588e9f
v1.4.5 c56a1e4b22071ac7b36c7bf3d2eb5d4e75588e9f
v1.4.4.2 635d24129c93d96d00c20b3727eae4c506707283
v1.4.4.1 b8ccda7415a67838ecfa7c01671f76cefe0c76de
v1.4.4 b8ccda7415a67838ecfa7c01671f76cefe0c76de
v1.4.3.1 e65853fb4f7afa7739b1c84863c4737c034d66bb
v1.4.3 e65853fb4f7afa7739b1c84863c4737c034d66bb
v1.4.2 0ca3ce1558257c596de5a9158673373a0ad81a23
v1.4.1 dbfac936dae5e137820833ce54cbfd804bb647b4
v1.4.0 8f1cb6faa76497f63c5a1a4ecf8cfbf9dcee1f76
```

PLEASE do spot check my work and make sure I haven't made some erroneous assumption. Basically I looked at [the nokogiri tagged releases](https://github.com/sparklemotion/nokogiri/releases), noted their dates, then looked at the commits in this repo and found the latest commit that would have existed when the nokogiri release was tagged. 

Multiple version tags *will* point to the same commit in this repo when this repo did not see any changes between versions; I figured having multiple tags on the same commit was less confusing than having versions missing, since people will be looking for the version of nokogiri they have.

I did not do any RCs or debian-specific versions; I happily will if you think someone out there would find them useful :)

**Comment by flavorjones** [comment]
Thanks! Will do something with these commits soon ...

**Comment by franklinyu** [comment]
Nokogiri seems to follow a version scheme similar to [Semantic Versioning](http://semver.org/), so we don't even need to tag every version. It's sufficient to have branches like `v1.5.x`, `v1.6.4.x`, `v1.6.6.x`, and `v1.6.7.x`, just like in the main repository.
