### ISSUE TITLE
code snippet syntax highlight

### ISSUE THREAD

**Issue by franklinyu** [sparklemotion/nokogiri.org-tutorials#51]
For example the two snippets [here](https://github.com/sparklemotion/nokogiri.org-tutorials/blob/master/content/installing_nokogiri.md#troubleshooting-native-windows-compilation) should have been plain text, but are now renderred as shell script. I'm not familiar with Octopress, but according to [the documentation](http://octopress.org/docs/plugins/backtick-codeblock/) labeling them with `plain` seems to suffice.

**Comment by flavorjones** [comment]
I'm sorry, I'm not sure I understand what you're saying here. The snippets render as plaintext for me. Can you help me understand?

**Comment by franklinyu** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/3153452/25974318/768bb5a8-3676-11e7-9f8a-70609d6e2ffd.png)

I see this on latest Chrome on macOS Sierra.

**Comment by flavorjones** [comment]
Ah! I see it now. Roger.

**Comment by flavorjones** [comment]
Closing, this page was rewritten and no longer contains this antipattern. Thanks again for pointing it out!
