### ISSUE TITLE
Incorporate "how to extract HTML features using xpath and css" into tutorial

### ISSUE THREAD

**Issue by rdpoor** [sparklemotion/nokogiri.org-tutorials#58]
A while back, I wrote a Nokogiri tutorial disguised as a StackOverflow response on "how to extract HTML features using xpath and css":

    https://stackoverflow.com/a/20284975/558639

It shows in substantial detail how to extract links from HTML, find a specific link, find a link from associated text, extract text from a link.  And it shows how to do each of those using xpath and css constructs.

I opine that this would be a welcome addition to the tutorial documentation.

I'm not psychically prepared to learn the sparklemotion stuff to incorporated this into the tutorial, but it should be an easy task for someone who is.

**Comment by flavorjones** [comment]
moving to https://github.com/sparklemotion/nokogiri.org/issues/18
