### ISSUE TITLE
Compatibility with Xpath2 and Xpath2

### ISSUE THREAD

**Issue by aksjain** [sparklemotion/nokogiri.org-tutorials#60]

**Comment by flavorjones** [comment]
Hi, @aksjain!

Can you provide a bit more context around why you opened this issue? As you may know, Nokogiri doesn't support XPath 2.0, so if you could please help me understand what problem you're facing, that will tell me what, if anything, we can document better.

Thanks!

**Comment by aksjain** [comment]
Hi Mike,

I am trying to process documents using the XPath. But I believe we can write much simpler XPath code if Nokogiri supports Xpath2 or Xpath3. This ticket is not reporting a bug, it is more of a feature request to support XPath2 or XPath3 in future. I want to know if there is a plan to accommodate Xpath2 or Xpath3 in future?

**Comment by flavorjones** [comment]
This repository contains the nokogiri tutorials found at nokogiri.org. If you'd like to discuss a nokogiri feature, please open an issue at https://github.com/sparklemotion/nokogiri

Thanks!
